version: '3.8'
services:
  frontserver:
    container_name: ba_front_prod
    image: clemrz/bitcoin-analyzer-front:prod
    build:
      context: ../bitcoin-analyzer-front/
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    depends_on:
      - backserver
      - dbserver
      - migrations
    networks:
      - ba_ntw

networks:
  ba_ntw:
    driver: bridge